### ISSUE TITLE
InsideOut component

### ISSUE THREAD

**Issue by stefanzurich** [odtp-org/odtp#131]
- **InsideOut component**

## Description:
Implementing InsideOut project methods in the ODTP 

## Importance Level
High

## User Impact
The component will rely on Eqasim input and will run Matsim within itself. The new component will assigns AV mode to the roads in the network in order to optimize AV infrastructure by evaluating which roads should be used only for AVs,

## Affected Components (examples: components, modules, … )
Matsim component should be modified so that it allows AV as a transport mode.

## Related Documents/Links: 
https://github.com/idsc-frazzoli/inside-out-odtp

**Comment by jugdemon** [comment]
Inside out component development has been conducted by @albma352. I think the component is currently still private but I will follow up on the component with marc.
