### ISSUE TITLE
[Installation] Failure to execute ODTP image

### ISSUE THREAD

**Issue by albma352** [odtp-org/odtp#140]
## Environment

- **ODTP/ODTP Component version:** 0.2.8
- **Operating System:** Ubuntu 22.04
- **Browser:** (if applicable)

### Summary:
`docker compose build --no-cache` builds the container successfully. However, when running the next step `docker exec -it odtp-odtp-1 odtp setup initiate` an error message is displayed: `Error response from daemon: No such container: odtp-odtp-1`. 

### Steps to reproduce the bug:
1. Follow [tutorial](https://odtp-org.github.io/odtp-manuals/installation/docker-compose_install/) on ubuntu until step 7
2. 

### Supporting information
There is a docker container named `odtp` visible when running `docker image ls` however, even when changing the command that fails to run to `docker exec -it odtp odtp setup initiate` a similar error message is shown (odtp container not found).

**Comment by caviri** [comment]
Hello @albma352, sorry for the delay. 

Thanks for trying the tutorial. I recognize that the documentation has not been updated. Can you try the following: 


6. Build the docker containers

```
docker-compose build --no-cache  
```

Now you can run the component with

```
docker compose up -d
```

Then run the tool in the CLI or the GUI using the following: 

```
docker exec -it odtp-odtp-1 sh
```

or 


```
docker exec -it odtp-odtp-1 odtp dashboard 
```

**Comment by albma352** [comment]
Hi @caviri, thank you for your reply. This resolved the issue. Thank you. 
fyi @jugdemon
