### ISSUE TITLE
path format error in Windows system

### ISSUE THREAD

**Issue by peiling24** [odtp-org/odtp#177]
## Environment

- **ODTP/ODTP Component version:0.2.8
- **Operating System: Microsoft Windows 10 Education

### Summary:
Windows path format error:

[+] Running 0/0
 - Container odtp-odtp-1  Creating                                                                                 0.0s
Error response from daemon: mount denied:
the source path "/Users/peiling/OneDrive - KTH/CITWIN/Open Digital Twin Platform/odtp/odtp:C:/Users/peiling/OneDrive - KTH/CITWIN/Open Digital Twin Platform/odtp/odtp:rw"
too many colons

### Steps to reproduce the bug:
Follow [tutorial](https://odtp-org.github.io/odtp-manuals/installation/docker-compose_install/) on ubuntu until step 7

**Comment by peiling24** [comment]
It was resolved by converting my paths to Linux format in .env file:

# absolute path for docker volumes
ODTP_PATH="/mnt/c/Users/peiling/OneDrive - KTH/CITWIN/Open Digital Twin Platform/odtp/odtp"

**Comment by sabinem** [comment]
@peiling24 Glad you could fix this on your side. I am closing the issue.
