### ISSUE TITLE
dataset switch link- corsica (simple test)

### ISSUE THREAD

**Issue by gloglo13** [odtp-org/odtp#196]
For test my local instalation, i would like to have access to the parameters for running corsica use case. in the documentation for this example i read:
> **Important:** To run this dataset, you need to have the initial dataset switch link. Please ensure you have access to the original dataset before starting. Open an issue to request it.

who can help me?
I am using as user my gmail e-mail: gloria.romera@gmail.com ( is that ok?)

**Comment by sabinem** [comment]
@gloglo13 I will send the link to you.
